experiments:
- chi: 8
  num_sites: 28
  run_type: periodic
- chi: 8
  num_sites: 38
  run_type: periodic
- chi: 10
  num_sites: 22
  run_type: periodic
- chi: 10
  num_sites: 24
  run_type: periodic
- chi: 10
  num_sites: 26
  run_type: periodic
- chi: 10
  num_sites: 28
  run_type: periodic
- chi: 10
  num_sites: 36
  run_type: periodic
- chi: 10
  num_sites: 48
  run_type: periodic
- chi: 12
  num_sites: 16
  run_type: periodic
- chi: 12
  num_sites: 18
  run_type: periodic
- chi: 12
  num_sites: 22
  run_type: periodic
- chi: 12
  num_sites: 26
  run_type: periodic
- chi: 12
  num_sites: 28
  run_type: periodic
- chi: 12
  num_sites: 34
  run_type: periodic
- chi: 12
  num_sites: 36
  run_type: periodic
- chi: 12
  num_sites: 38
  run_type: periodic
- chi: 12
  num_sites: 40
  run_type: periodic
- chi: 12
  num_sites: 42
  run_type: periodic
- chi: 12
  num_sites: 44
  run_type: periodic
- chi: 12
  num_sites: 46
  run_type: periodic
- chi: 12
  num_sites: 48
  run_type: periodic
- chi: 14
  num_sites: 8
  run_type: periodic
- chi: 14
  num_sites: 10
  run_type: periodic
- chi: 14
  num_sites: 24
  run_type: periodic
- chi: 14
  num_sites: 28
  run_type: periodic
- chi: 14
  num_sites: 34
  run_type: periodic
- chi: 14
  num_sites: 44
  run_type: periodic
- chi: 16
  num_sites: 10
  run_type: periodic
- chi: 16
  num_sites: 14
  run_type: periodic
- chi: 16
  num_sites: 20
  run_type: periodic
- chi: 16
  num_sites: 24
  run_type: periodic
- chi: 16
  num_sites: 26
  run_type: periodic
- chi: 16
  num_sites: 28
  run_type: periodic
- chi: 16
  num_sites: 30
  run_type: periodic
- chi: 16
  num_sites: 34
  run_type: periodic
- chi: 16
  num_sites: 38
  run_type: periodic
- chi: 16
  num_sites: 44
  run_type: periodic
- chi: 16
  num_sites: 46
  run_type: periodic
- chi: 16
  num_sites: 48
  run_type: periodic
- chi: 18
  num_sites: 6
  run_type: periodic
- chi: 18
  num_sites: 10
  run_type: periodic
- chi: 18
  num_sites: 20
  run_type: periodic
- chi: 18
  num_sites: 28
  run_type: periodic
- chi: 18
  num_sites: 34
  run_type: periodic
- chi: 18
  num_sites: 40
  run_type: periodic
- chi: 18
  num_sites: 46
  run_type: periodic
- chi: 18
  num_sites: 48
  run_type: periodic
- chi: 20
  num_sites: 8
  run_type: periodic
- chi: 20
  num_sites: 12
  run_type: periodic
- chi: 20
  num_sites: 16
  run_type: periodic
- chi: 20
  num_sites: 22
  run_type: periodic
- chi: 20
  num_sites: 28
  run_type: periodic
- chi: 20
  num_sites: 30
  run_type: periodic
- chi: 20
  num_sites: 36
  run_type: periodic
- chi: 20
  num_sites: 40
  run_type: periodic
- chi: 20
  num_sites: 42
  run_type: periodic
- chi: 20
  num_sites: 46
  run_type: periodic
- chi: 22
  num_sites: 4
  run_type: periodic
- chi: 22
  num_sites: 20
  run_type: periodic
- chi: 22
  num_sites: 28
  run_type: periodic
- chi: 22
  num_sites: 34
  run_type: periodic
- chi: 22
  num_sites: 40
  run_type: periodic
- chi: 22
  num_sites: 46
  run_type: periodic
- chi: 24
  num_sites: 10
  run_type: periodic
- chi: 24
  num_sites: 22
  run_type: periodic
- chi: 24
  num_sites: 30
  run_type: periodic
- chi: 24
  num_sites: 38
  run_type: periodic
- chi: 24
  num_sites: 44
  run_type: periodic
- chi: 24
  num_sites: 48
  run_type: periodic
max_iter: 1000000.0
param: 1.0
resume: true
