experiments:
- chi: 4
  num_sites: 4
  run_type: uniform
- chi: 6
  num_sites: 4
  run_type: uniform
- chi: 8
  num_sites: 4
  run_type: uniform
- chi: 10
  num_sites: 4
  run_type: uniform
- chi: 12
  num_sites: 4
  run_type: uniform
- chi: 14
  num_sites: 4
  run_type: uniform
- chi: 16
  num_sites: 4
  run_type: uniform
- chi: 18
  num_sites: 4
  run_type: uniform
- chi: 20
  num_sites: 4
  run_type: uniform
- chi: 22
  num_sites: 4
  run_type: uniform
- chi: 24
  num_sites: 4
  run_type: uniform
- chi: 4
  num_sites: 6
  run_type: uniform
- chi: 6
  num_sites: 6
  run_type: uniform
- chi: 8
  num_sites: 6
  run_type: uniform
- chi: 10
  num_sites: 6
  run_type: uniform
- chi: 12
  num_sites: 6
  run_type: uniform
- chi: 14
  num_sites: 6
  run_type: uniform
- chi: 16
  num_sites: 6
  run_type: uniform
- chi: 18
  num_sites: 6
  run_type: uniform
- chi: 20
  num_sites: 6
  run_type: uniform
- chi: 22
  num_sites: 6
  run_type: uniform
- chi: 24
  num_sites: 6
  run_type: uniform
- chi: 4
  num_sites: 8
  run_type: uniform
- chi: 6
  num_sites: 8
  run_type: uniform
- chi: 8
  num_sites: 8
  run_type: uniform
- chi: 10
  num_sites: 8
  run_type: uniform
- chi: 12
  num_sites: 8
  run_type: uniform
- chi: 14
  num_sites: 8
  run_type: uniform
- chi: 16
  num_sites: 8
  run_type: uniform
- chi: 18
  num_sites: 8
  run_type: uniform
- chi: 20
  num_sites: 8
  run_type: uniform
- chi: 22
  num_sites: 8
  run_type: uniform
- chi: 24
  num_sites: 8
  run_type: uniform
- chi: 4
  num_sites: 10
  run_type: uniform
- chi: 6
  num_sites: 10
  run_type: uniform
- chi: 8
  num_sites: 10
  run_type: uniform
- chi: 10
  num_sites: 10
  run_type: uniform
- chi: 12
  num_sites: 10
  run_type: uniform
- chi: 14
  num_sites: 10
  run_type: uniform
- chi: 16
  num_sites: 10
  run_type: uniform
- chi: 18
  num_sites: 10
  run_type: uniform
- chi: 20
  num_sites: 10
  run_type: uniform
- chi: 22
  num_sites: 10
  run_type: uniform
- chi: 24
  num_sites: 10
  run_type: uniform
- chi: 4
  num_sites: 12
  run_type: uniform
- chi: 6
  num_sites: 12
  run_type: uniform
- chi: 8
  num_sites: 12
  run_type: uniform
- chi: 10
  num_sites: 12
  run_type: uniform
- chi: 12
  num_sites: 12
  run_type: uniform
- chi: 14
  num_sites: 12
  run_type: uniform
- chi: 16
  num_sites: 12
  run_type: uniform
- chi: 18
  num_sites: 12
  run_type: uniform
- chi: 20
  num_sites: 12
  run_type: uniform
- chi: 22
  num_sites: 12
  run_type: uniform
- chi: 24
  num_sites: 12
  run_type: uniform
- chi: 4
  num_sites: 14
  run_type: uniform
- chi: 6
  num_sites: 14
  run_type: uniform
- chi: 8
  num_sites: 14
  run_type: uniform
- chi: 10
  num_sites: 14
  run_type: uniform
- chi: 12
  num_sites: 14
  run_type: uniform
- chi: 14
  num_sites: 14
  run_type: uniform
- chi: 16
  num_sites: 14
  run_type: uniform
- chi: 18
  num_sites: 14
  run_type: uniform
- chi: 20
  num_sites: 14
  run_type: uniform
- chi: 22
  num_sites: 14
  run_type: uniform
- chi: 24
  num_sites: 14
  run_type: uniform
- chi: 4
  num_sites: 16
  run_type: uniform
- chi: 6
  num_sites: 16
  run_type: uniform
- chi: 8
  num_sites: 16
  run_type: uniform
- chi: 10
  num_sites: 16
  run_type: uniform
- chi: 12
  num_sites: 16
  run_type: uniform
- chi: 14
  num_sites: 16
  run_type: uniform
- chi: 16
  num_sites: 16
  run_type: uniform
- chi: 18
  num_sites: 16
  run_type: uniform
- chi: 20
  num_sites: 16
  run_type: uniform
- chi: 22
  num_sites: 16
  run_type: uniform
- chi: 24
  num_sites: 16
  run_type: uniform
- chi: 4
  num_sites: 18
  run_type: uniform
- chi: 6
  num_sites: 18
  run_type: uniform
- chi: 8
  num_sites: 18
  run_type: uniform
- chi: 10
  num_sites: 18
  run_type: uniform
- chi: 12
  num_sites: 18
  run_type: uniform
- chi: 14
  num_sites: 18
  run_type: uniform
- chi: 16
  num_sites: 18
  run_type: uniform
- chi: 18
  num_sites: 18
  run_type: uniform
- chi: 20
  num_sites: 18
  run_type: uniform
- chi: 22
  num_sites: 18
  run_type: uniform
- chi: 24
  num_sites: 18
  run_type: uniform
- chi: 4
  num_sites: 20
  run_type: uniform
- chi: 6
  num_sites: 20
  run_type: uniform
- chi: 8
  num_sites: 20
  run_type: uniform
- chi: 10
  num_sites: 20
  run_type: uniform
- chi: 12
  num_sites: 20
  run_type: uniform
- chi: 14
  num_sites: 20
  run_type: uniform
- chi: 16
  num_sites: 20
  run_type: uniform
- chi: 18
  num_sites: 20
  run_type: uniform
- chi: 20
  num_sites: 20
  run_type: uniform
- chi: 22
  num_sites: 20
  run_type: uniform
- chi: 24
  num_sites: 20
  run_type: uniform
- chi: 4
  num_sites: 22
  run_type: uniform
- chi: 6
  num_sites: 22
  run_type: uniform
- chi: 8
  num_sites: 22
  run_type: uniform
- chi: 10
  num_sites: 22
  run_type: uniform
- chi: 12
  num_sites: 22
  run_type: uniform
- chi: 14
  num_sites: 22
  run_type: uniform
- chi: 16
  num_sites: 22
  run_type: uniform
- chi: 18
  num_sites: 22
  run_type: uniform
- chi: 20
  num_sites: 22
  run_type: uniform
- chi: 22
  num_sites: 22
  run_type: uniform
- chi: 24
  num_sites: 22
  run_type: uniform
- chi: 4
  num_sites: 24
  run_type: uniform
- chi: 6
  num_sites: 24
  run_type: uniform
- chi: 8
  num_sites: 24
  run_type: uniform
- chi: 10
  num_sites: 24
  run_type: uniform
- chi: 12
  num_sites: 24
  run_type: uniform
- chi: 14
  num_sites: 24
  run_type: uniform
- chi: 16
  num_sites: 24
  run_type: uniform
- chi: 18
  num_sites: 24
  run_type: uniform
- chi: 20
  num_sites: 24
  run_type: uniform
- chi: 22
  num_sites: 24
  run_type: uniform
- chi: 24
  num_sites: 24
  run_type: uniform
- chi: 4
  num_sites: 26
  run_type: uniform
- chi: 6
  num_sites: 26
  run_type: uniform
- chi: 8
  num_sites: 26
  run_type: uniform
- chi: 10
  num_sites: 26
  run_type: uniform
- chi: 12
  num_sites: 26
  run_type: uniform
max_iter: 1000000
param: 1.0
resume: false
